### ISSUE TITLE
Create shift chart

### ISSUE THREAD

**Issue by amandrycky** [war-on-ice/war-on-ice#5]
Need a shift chart like this:
![image](https://cloud.githubusercontent.com/assets/2133629/9827615/cbe07aa6-5898-11e5-8f50-dcd64389c18a.png)

**Comment by kevkan** [comment]
I'll start working on this by cleaning up and modifying an old project. I'll be using a common x-axis with the running tallies chart so if they're displayed on top of each other, you can kind of correlate them.
